import { createContext, useState } from "react";

// Create the context
export const ProductContext = createContext();

// Provider component
export const ProductProvider = ({ children }) => {
  const [products, setProducts] = useState([
    {
      id: 0,
      name: "VINTAGE LOGO HOODIE [white]",
      price: "1299.00",
      image: "/product1.jpg",
      type: "top",
      material: "cotton",
      colors: "White",
      size: "M",
      availableSizes: ["S", "M", "L", "XL"],
      season: "winter",
      fasteners: "pullover",
      collection: "new",
      fitting: "Oversized",
      detail:
        "Premium cotton hoodie featuring vintage logo design with a soft brushed inner layer.",
      description:
        "Stay cozy in our Vintage Logo Hoodie. Crafted from high-quality cotton, it features a clean white tone, oversized fit, and iconic logo detail—perfect for chilly winter days.",
    },
    {
      id: 1,
      name: "RUGED HOODIE [blue]",
      price: "1299.00",
      image: "/product3.jpg",
      type: "top",
      material: "cotton",
      colors: "Blue",
      size: "L",
      availableSizes: ["S", "M", "L", "XL"],
      season: "winter",
      fasteners: "pullover",
      collection: "old",
      fitting: "Oversized",
      detail:
        "Classic blue cotton hoodie with a pullover and a relaxed fit for winter layering.",
      description:
        "The RUGED HOODIE offers versatility and comfort with its oversized silhouette and smooth zip closure, ideal for everyday streetwear looks.",
    },
    {
      id: 2,
      name: "ESSENTIAL HOODIE [Brown]",
      price: "1099.00",
      image: "/product2.jpg",
      type: "top",
      material: "cotton",
      colors: "Brown",
      size: "L",
      availableSizes: ["M", "L", "XL"],
      season: "winter",
      fasteners: "pullover",
      collection: "new",
      fitting: "Oversized",
      detail:
        "A winter essential crafted in soft brown cotton with minimal branding and maximum comfort.",
      description:
        "Layer in style with our Essential Hoodie—made for warmth and ease. The earthy tone pairs effortlessly with your cold-weather fits.",
    },
    {
      id: 3,
      name: "CLASSIC HOODIE",
      price: "999.00",
      image: "/zipper hoodie.jpg",
      type: "top",
      material: "cotton",
      colors: "Blue",
      size: "M",
      availableSizes: ["S", "M", "L", "XL"],
      season: "winter",
      fasteners: "zipper",
      collection: "new",
      fitting: "Oversized",
      detail:
        "Timeless hoodie featuring front zipper, heavy-weight cotton, and relaxed shoulders.",
      description:
        "With classic design and durability, this hoodie blends form and function. The zip-up style offers adjustable comfort for the winter chill.",
    },
    {
      id: 4,
      name: "GRAPHIC HOODIE [Black]",
      price: "1199.00",
      image: "/black hoodie.jpg",
      type: "top",
      material: "cotton",
      colors: "Black",
      size: "L",
      availableSizes: ["M", "L", "XL"],
      season: "winter",
      fasteners: "zipper",
      collection: "old",
      fitting: "fit",
      detail: "Black graphic hoodie with a sleek fit and streetwear edge.",
      description:
        "Turn heads with the Graphic Hoodie featuring standout visuals, clean lines, and a snug, modern fit. Built for urban fashion.",
    },
    {
      id: 5,
      name: "Classic Black Tee",
      image: "/Black over.jpg",
      type: "top",
      price: "1199.00",
      subcategory: "tshirt",
      material: "Cotton",
      colors: "Black",
      season: "Summer",
      collection: "old",
      availableSizes: ["S", "M", "L", "XL"],
      fitting: "Oversized",
      detail:
        "Minimalist oversized tee in rich black cotton for everyday comfort.",
      description:
        "Our Classic Black Tee redefines essential wear. Its breathable cotton fabric and oversized design ensure all-day coolness in the summer heat.",
    },
    {
      id: 6,
      name: "White Logo Tee",
      image: "/white t-shirt.jpg",
      type: "top",
      price: "1199.00",
      subcategory: "tshirt",
      material: "Cotton",
      colors: "White",
      season: "Summer",
      collection: "old",
      availableSizes: ["M", "L", "XL"],
      fitting: "Oversized",
      detail:
        "White cotton tee with a subtle logo print and a boxy silhouette.",
      description:
        "Showcase your style with the White Logo Tee. Its lightweight cotton build and relaxed fit offer a breathable feel and clean aesthetic.",
    },
    {
      id: 7,
      name: "Oversized Grey Tee",
      image: "/ruged t-shirt.jpg",
      type: "top",
      price: "1199.00",
      subcategory: "tshirt",
      material: "cotton",
      colors: "Grey",
      season: "Spring",
      collection: "new",
      availableSizes: ["S", "L", "XL"],
      fitting: "Oversized",
      detail:
        "Washed grey tee made with soft-touch fabric and a laid-back spring vibe.",
      description:
        "Bring comfort and versatility to your wardrobe with this Oversized Grey Tee. Its muted tones and easy fit make it a daily go-to.",
    },
    {
      id: 8,
      name: "Minimal green Tee",
      image: "/green t-shirt.jpg",
      type: "top",
      price: "1199.00",
      subcategory: "tshirt",
      material: "Cotton",
      colors: "Green",
      season: "Summer",
      collection: "new",
      availableSizes: ["M", "L"],
      fitting: "Oversized",
      detail:
        "Muted green oversized tee with a breathable cotton weave perfect for hot days.",
      description:
        "Stay cool in style with our Minimal Green Tee. It features a relaxed structure and subtle tone ideal for summer minimalism.",
    },
    {
      id: 9,
      name: "BB Quote Tee",
      image: "/t2.jpg",
      type: "top",
      price: "1199.00",
      subcategory: "tshirt",
      material: "Nylon",
      colors: "White",
      season: "Summer",
      collection: "old",
      availableSizes: ["S", "M", "XL"],
      fitting: "fit",
      detail: "Fitted nylon tee with a bold quote print and soft elastic feel.",
      description:
        "Make a statement with the BB Quote Tee. Its sharp fit and expressive quote design set you apart in any crowd.",
    },
    {
      id: 10,
      name: "yoythiyapa t-shirt",
      image: "/t4.jpg",
      type: "top",
      price: "1199.00",
      subcategory: "tshirt",
      material: "Cotton",
      colors: "Black",
      season: "Spring",
      collection: "new",
      availableSizes: ["L", "XL"],
      fitting: "fit",
      detail:
        "Black spring tee with Youthiyapa branding and tailored silhouette.",
      description:
        "Express your vibe in the Yoythiyapa Tee. Its comfy cotton and bold identity strike the perfect balance of cool and confident.",
    },
    {
      id: 11,
      name: "Classic Brown Cargo",
      image: "/brown pent.jpg",
      type: "bottom",
      price: "1399.00",
      subcategory: "pants",
      material: "Cotton",
      colors: "Black",
      season: "Winter",
      collection: "old",
      availableSizes: ["S", "M", "L", "XL"],
      fitting: "Oversized",
      detail:
        "Utility-style black cargo with multiple pockets and durable winter cotton.",
      description:
        "Whether you're exploring or lounging, the Classic Brown Cargo keeps you comfortable with a roomy cut and functional design.",
    },
    {
      id: 12,
      name: "Slim Fit Blue Denims",
      image: "/blue denim.jpg",
      type: "bottom",
      price: "1499.00",
      subcategory: "pants",
      material: "Denim",
      colors: "Blue",
      season: "Spring",
      collection: "new",
      availableSizes: ["M", "L", "XL"],
      fitting: "relaxed",
      detail:
        "Sleek mid-wash blue jeans with a modern slim-relaxed hybrid fit.",
      description:
        "Upgrade your jeans game with our Slim Fit Denims. They combine denim toughness with a spring-ready breathable fit.",
    },
    {
      id: 13,
      name: "Ruged Cargo Pants [Gray]",
      image: "/gray cargo.jpg",
      type: "bottom",
      price: "1599.00",
      subcategory: "pants",
      material: "Denim",
      colors: "Green",
      season: "Summer",
      collection: "old",
      availableSizes: ["S", "M", "L"],
      fitting: "relaxed",
      detail:
        "Utility denim cargo in rugged green with reinforced stitching and adjustable hem.",
      description:
        "Built for bold moves, the Rugged Cargo Pants provide form and flexibility in warm weather with a utilitarian edge.",
    },
    {
      id: 14,
      name: "Gray cargo[Grey]",
      image: "/caro.jpg",
      type: "bottom",
      price: "1299.00",
      subcategory: "pants",
      material: "Nylon",
      colors: "Grey",
      season: "Spring",
      collection: "new",
      availableSizes: ["M", "L", "XL"],
      fitting: "relaxed",
      detail:
        "Breathable grey nylon cargos designed with mobility and lightweight wear in mind.",
      description:
        "Step out in comfort with Gray Cargos—ideal for spring with their relaxed fit and lightweight build.",
    },
    {
      id: 15,
      name: "Streetwear Track Pants",
      image: "/cargo3.jpg",
      type: "bottom",
      price: "1199.00",
      subcategory: "pants",
      material: "Nylon",
      colors: "White",
      season: "Summer",
      collection: "new",
      availableSizes: ["S", "M", "L", "XL"],
      fitting: "relaxed",
      detail:
        "White track pants with elastic waistband and clean minimalist aesthetics.",
      description:
        "These track pants deliver urban comfort with a sporty twist—perfect for hot days and laid-back vibes.",
    },
    {
      id: 16,
      name: "Logo Baseball Cap [blue]",
      image: "/accessories5.webp",
      type: "accessories",
      price: "499.00",
      subcategory: "cap",
      material: "Cotton",
      colors: "Blue",
      season: "Summer",
      collection: "old",
      availableSizes: ["Free Size"],
      fitting: "",
      detail:
        "Classic blue cap featuring adjustable strap and embroidered branding.",
      description:
        "Top off your look with our Logo Baseball Cap. Lightweight and breathable, it's a summer essential.",
    },
    {
      id: 17,
      name: "BB Calander",
      image: "/accessories2.webp",
      type: "accessories",
      price: "899.00",
      subcategory: "calendar",
      colors: "Green",
      season: "Spring",
      collection: "new",
      availableSizes: ["One Size"],
      fitting: "",
      detail:
        "BB-branded desk calendar with sleek, minimalist layout and durable print.",
      description:
        "Stay organized and inspired year-round with the BB Calendar. A perfect desk companion for every fan.",
    },
    {
      id: 18,
      name: "Utility Keychain Lanyard",
      image: "/accessories1.webp",
      type: "accessories",
      price: "199.00",
      subcategory: "keychain",
      material: "Nylon",
      colors: "Black",
      season: "All Season",
      collection: "new",
      availableSizes: ["One Size"],
      fitting: "",
      detail: "Heavy-duty black keychain with woven strap and metal clip.",
      description:
        "Keep your keys in check with the Utility Keychain. Durable, stylish, and built for everyday use.",
    },
    {
      id: 19,
      name: "BB Branded Mug [White]",
      image: "/accessories4.webp",
      type: "accessories",
      price: "159.00",
      subcategory: "mug",
      colors: "White",
      season: "Winter",
      collection: "old",
      availableSizes: ["M", "L"],
      fitting: "",
      detail:
        "Classic ceramic mug with BB branding—dishwasher safe and heat resistant.",
      description:
        "Sip your coffee in style with the BB Branded Mug. A perfect blend of simplicity and character.",
    },
  ]);

  return (
    <ProductContext.Provider value={{ products, setProducts }}>
      {children}
    </ProductContext.Provider>
  );
};
